---
title: "Nordrhein-Westfalen"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, rows.print = 5)
library(ggplot2)
library(tidyverse)
library(readxl)
library(janitor)
library(reactable)
library(htmltools)
nrw_full <- readRDS("output/state/nrw.rds")
```

```{r print, layout = "l-page"}
nrw_summary <- nrw_full %>%
  mutate(
    wkr = paste(wkr_nr, " (", wkr_name, ")", sep = ""),
    location = paste(plz, city)
  ) %>%
  group_by(beneficiary, location) %>%
  summarize(
    objectives = toString(unique(eso_objective)),
    total_funding = sum(eu_cost),
    wkr = toString(unique(wkr)),
    land = toString(unique(land_name))
  ) %>%
  ungroup() %>%
  select(
    beneficiary, objectives, total_funding, location, everything()
  )

htmltools::browsable(
  tagList(
    reactable(nrw_summary,
  filterable = TRUE,
  columns = list(
    beneficiary = colDef(name = "Begünstigte", align = "left", minWidth = 200),
    location = colDef(name = "Standort", aggregate = "unique", align = "right"),
    objectives = colDef(name = "Ziele", aggregate = "unique", align = "left"),
    total_funding = colDef(name = "EU-Fördermittel", aggregate = "sum", align = "right", format = colFormat(prefix = "€", separators = TRUE, digits = 2, locales = "de-DE")),
    wkr = colDef(name = "Wahlkreis", aggregate = "unique", align = "right"),
    land = colDef(name = "Land", aggregate = "unique", align = "right")
  ),
  defaultPageSize = 5,
  paginationType = "jump",
  highlight = TRUE,
  bordered = TRUE, 
  striped = TRUE,
  defaultSorted = list(total_funding = "desc"),
  elementId = "main-table"
),
    tags$button(
      tagList(fontawesome::fa("download"), "Download as CSV"),
      onclick = "Reactable.downloadDataCSV('main-table', 'download.csv')"
    )
)
)
```

